export const products = [
    {
      id: 0,
      inStock: false,
      title: "Shoes Spring",
      price: 55,
      quantity: 5,
      imgSrc: require("../Images/product/product-1.jpg"),
      desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    },
    {
      id: 1,
      inStock: true,
      title: "BikerJacket",
      price: 55,
      quantity: 5,
      imgSrc: require("../Images/product/product-2.jpg"),
      desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    },
    {
      id: 2,
      inStock: 0,
      title: "Shoes Spring",
      price: 55,
      quantity: 5,
      imgSrc: require("../Images/product/product-3.jpg"),
      desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    },
    {
      id: 3,
      inStock: 8,
  
      title: "BikerJacket",
      price: 59,
      quantity: 5,
      imgSrc: require("../Images/product/product-4.jpg"),
      desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    },
    {
      id: 4,
      inStock: 1,
      title: "T-Shirt",
      price: 55,
      quantity: 5,
      imgSrc:require("../Images/product/product-5.jpg"),
      desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    },
    {
      id: 5,
      inStock: 1,
  
      title: "Shoes Spring",
      price: 55,
      quantity: 5,
      imgSrc:require("../Images/product/product-6.jpg"),
      desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    },
    {
      id: 6,
      title: "Tea",
      price: 55,
      quantity: 5,
      imgSrc:require("../Images/product/product-7.jpg"),
      inStock: false,
  
      desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    },
    {
      id: 7,
      inStock: 1,
      title:" T-Shirt",
      price: 55,
      quantity: 5,
      imgSrc:require("../Images/product/product-8.jpg"),
  
      desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
    },
    {
        id: 8,
        inStock: 1,
        title:" T-Shirt",
        price: 55,
        quantity: 5,
        imgSrc:require("../Images/product/product-9.jpg"),
    
        desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
      },
      {
        id: 9,
        inStock: 1,
        title:" T-Shirt",
        price: 55,
        quantity: 5,
        imgSrc:require("../Images/product/product-10.jpg"),
        desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
      },
      {
        id: 10,
        inStock: 1,
        title:" T-Shirt",
        price: 55,
        quantity: 5,
        imgSrc:require("../Images/product/product-11.jpg"),
        desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
      },
      {
        id: 11,
        inStock: 1,
        title:" T-Shirt",
        price: 55,
        quantity: 5,
        imgSrc:require("../Images/product/product-12.jpg"),
        desc: "Some quick example text to build on the card title and make up the bulk of the card's content.",
      },
  ];
  